CREATE TABLE IF NOT EXISTS streak_reward_rule (
  reward_rule_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  module_id BIGINT UNSIGNED NOT NULL,
  sponsor_user_id BIGINT UNSIGNED NOT NULL,
  sponsor_member_instance_id BIGINT UNSIGNED NOT NULL,
  target_type VARCHAR(16) NOT NULL,
  target_member_instance_id BIGINT UNSIGNED NULL,
  prize_title VARCHAR(40) NOT NULL,
  prize_description VARCHAR(160) NULL,
  win_probability_bps SMALLINT UNSIGNED NOT NULL,
  streak_days TINYINT UNSIGNED NOT NULL DEFAULT 7,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  terms_version VARCHAR(20) NOT NULL,
  expires_at DATETIME(3) NOT NULL,
  triggered_at DATETIME(3) NULL,
  cancelled_at DATETIME(3) NULL,
  active_sponsor_key VARCHAR(160) GENERATED ALWAYS AS (
    IF(status = 'active', CONCAT(module_id, ':', sponsor_member_instance_id), NULL)
  ) STORED,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (reward_rule_id),
  UNIQUE KEY uq_reward_rule_active_sponsor (active_sponsor_key),
  KEY idx_reward_rule_module_status_expiry (module_id, status, expires_at),
  CONSTRAINT fk_reward_rule_module FOREIGN KEY (module_id) REFERENCES life_module(module_id),
  CONSTRAINT fk_reward_rule_sponsor_user FOREIGN KEY (sponsor_user_id) REFERENCES user_account(user_id),
  CONSTRAINT fk_reward_rule_sponsor_member FOREIGN KEY (sponsor_member_instance_id) REFERENCES module_member(member_instance_id),
  CONSTRAINT fk_reward_rule_target_member FOREIGN KEY (target_member_instance_id) REFERENCES module_member(member_instance_id),
  CONSTRAINT chk_reward_rule_target CHECK (target_type IN ('all', 'member')),
  CONSTRAINT chk_reward_rule_status CHECK (status IN ('active', 'triggered', 'cancelled', 'expired')),
  CONSTRAINT chk_reward_rule_probability CHECK (win_probability_bps IN (2000, 5000, 8000, 10000)),
  CONSTRAINT chk_reward_rule_days CHECK (streak_days = 7)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS streak_reward_event (
  reward_event_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  reward_rule_id BIGINT UNSIGNED NOT NULL,
  module_id BIGINT UNSIGNED NOT NULL,
  trigger_record_id BIGINT UNSIGNED NOT NULL,
  sponsor_name_snapshot VARCHAR(64) NOT NULL,
  target_type VARCHAR(16) NOT NULL,
  prize_title_snapshot VARCHAR(40) NOT NULL,
  prize_description_snapshot VARCHAR(160) NULL,
  win_probability_bps SMALLINT UNSIGNED NOT NULL,
  window_start DATE NOT NULL,
  window_end DATE NOT NULL,
  qualification_snapshot JSON NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (reward_event_id),
  UNIQUE KEY uq_reward_event_rule (reward_rule_id),
  KEY idx_reward_event_module_created (module_id, created_at),
  CONSTRAINT fk_reward_event_rule FOREIGN KEY (reward_rule_id) REFERENCES streak_reward_rule(reward_rule_id),
  CONSTRAINT fk_reward_event_module FOREIGN KEY (module_id) REFERENCES life_module(module_id),
  CONSTRAINT fk_reward_event_record FOREIGN KEY (trigger_record_id) REFERENCES life_record(record_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS streak_reward_draw (
  reward_draw_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  reward_event_id BIGINT UNSIGNED NOT NULL,
  module_id BIGINT UNSIGNED NOT NULL,
  recipient_user_id BIGINT UNSIGNED NOT NULL,
  recipient_member_instance_id BIGINT UNSIGNED NOT NULL,
  result_type VARCHAR(16) NOT NULL,
  sticker_record_id BIGINT UNSIGNED NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'sealed',
  revealed_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (reward_draw_id),
  UNIQUE KEY uq_reward_draw_event_recipient (reward_event_id, recipient_member_instance_id),
  KEY idx_reward_draw_pending (recipient_user_id, module_id, status, created_at),
  CONSTRAINT fk_reward_draw_event FOREIGN KEY (reward_event_id) REFERENCES streak_reward_event(reward_event_id),
  CONSTRAINT fk_reward_draw_module FOREIGN KEY (module_id) REFERENCES life_module(module_id),
  CONSTRAINT fk_reward_draw_user FOREIGN KEY (recipient_user_id) REFERENCES user_account(user_id),
  CONSTRAINT fk_reward_draw_member FOREIGN KEY (recipient_member_instance_id) REFERENCES module_member(member_instance_id),
  CONSTRAINT fk_reward_draw_sticker_record FOREIGN KEY (sticker_record_id) REFERENCES life_record(record_id),
  CONSTRAINT chk_reward_draw_result CHECK (result_type IN ('gift', 'sticker')),
  CONSTRAINT chk_reward_draw_status CHECK (status IN ('sealed', 'revealed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
