UPDATE user_account SET last_login_at = DATE_ADD(last_login_at, INTERVAL 8 HOUR), created_at = DATE_ADD(created_at, INTERVAL 8 HOUR), updated_at = DATE_ADD(updated_at, INTERVAL 8 HOUR);
UPDATE auth_session SET expires_at = DATE_ADD(expires_at, INTERVAL 8 HOUR), last_seen_at = DATE_ADD(last_seen_at, INTERVAL 8 HOUR), revoked_at = DATE_ADD(revoked_at, INTERVAL 8 HOUR), created_at = DATE_ADD(created_at, INTERVAL 8 HOUR);
UPDATE module_template SET created_at = DATE_ADD(created_at, INTERVAL 8 HOUR), updated_at = DATE_ADD(updated_at, INTERVAL 8 HOUR);
UPDATE life_module SET group_activated_at = DATE_ADD(group_activated_at, INTERVAL 8 HOUR), last_activity_at = DATE_ADD(last_activity_at, INTERVAL 8 HOUR), deleted_at = DATE_ADD(deleted_at, INTERVAL 8 HOUR), recycle_expire_at = DATE_ADD(recycle_expire_at, INTERVAL 8 HOUR), created_at = DATE_ADD(created_at, INTERVAL 8 HOUR), updated_at = DATE_ADD(updated_at, INTERVAL 8 HOUR);
UPDATE module_member SET joined_at = DATE_ADD(joined_at, INTERVAL 8 HOUR), left_at = DATE_ADD(left_at, INTERVAL 8 HOUR), created_at = DATE_ADD(created_at, INTERVAL 8 HOUR), updated_at = DATE_ADD(updated_at, INTERVAL 8 HOUR);
UPDATE user_module_preference SET last_viewed_at = DATE_ADD(last_viewed_at, INTERVAL 8 HOUR), created_at = DATE_ADD(created_at, INTERVAL 8 HOUR), updated_at = DATE_ADD(updated_at, INTERVAL 8 HOUR);
UPDATE media_asset SET ready_at = DATE_ADD(ready_at, INTERVAL 8 HOUR), abandoned_at = DATE_ADD(abandoned_at, INTERVAL 8 HOUR), created_at = DATE_ADD(created_at, INTERVAL 8 HOUR), updated_at = DATE_ADD(updated_at, INTERVAL 8 HOUR);
UPDATE life_record SET first_effective_at = DATE_ADD(first_effective_at, INTERVAL 8 HOUR), approved_at = DATE_ADD(approved_at, INTERVAL 8 HOUR), locked_at = DATE_ADD(locked_at, INTERVAL 8 HOUR), deleted_at = DATE_ADD(deleted_at, INTERVAL 8 HOUR), created_at = DATE_ADD(created_at, INTERVAL 8 HOUR), updated_at = DATE_ADD(updated_at, INTERVAL 8 HOUR);
UPDATE record_revision SET created_at = DATE_ADD(created_at, INTERVAL 8 HOUR);
UPDATE reaction SET cancelled_at = DATE_ADD(cancelled_at, INTERVAL 8 HOUR), created_at = DATE_ADD(created_at, INTERVAL 8 HOUR), updated_at = DATE_ADD(updated_at, INTERVAL 8 HOUR);
UPDATE makeup_approval SET expire_at = DATE_ADD(expire_at, INTERVAL 8 HOUR), resolved_at = DATE_ADD(resolved_at, INTERVAL 8 HOUR), created_at = DATE_ADD(created_at, INTERVAL 8 HOUR), updated_at = DATE_ADD(updated_at, INTERVAL 8 HOUR);
UPDATE approval_action SET created_at = DATE_ADD(created_at, INTERVAL 8 HOUR);
UPDATE invite_token SET expire_at = DATE_ADD(expire_at, INTERVAL 8 HOUR), revoked_at = DATE_ADD(revoked_at, INTERVAL 8 HOUR), created_at = DATE_ADD(created_at, INTERVAL 8 HOUR), updated_at = DATE_ADD(updated_at, INTERVAL 8 HOUR);
UPDATE join_application SET expire_at = DATE_ADD(expire_at, INTERVAL 8 HOUR), reapply_allowed_at = DATE_ADD(reapply_allowed_at, INTERVAL 8 HOUR), resolved_at = DATE_ADD(resolved_at, INTERVAL 8 HOUR), created_at = DATE_ADD(created_at, INTERVAL 8 HOUR), updated_at = DATE_ADD(updated_at, INTERVAL 8 HOUR);
UPDATE notification SET read_at = DATE_ADD(read_at, INTERVAL 8 HOUR), expired_at = DATE_ADD(expired_at, INTERVAL 8 HOUR), created_at = DATE_ADD(created_at, INTERVAL 8 HOUR), updated_at = DATE_ADD(updated_at, INTERVAL 8 HOUR);
UPDATE module_inbox_item SET created_at = DATE_ADD(created_at, INTERVAL 8 HOUR), updated_at = DATE_ADD(updated_at, INTERVAL 8 HOUR), expire_at = DATE_ADD(expire_at, INTERVAL 8 HOUR);
UPDATE daily_module_snapshot SET calculated_at = DATE_ADD(calculated_at, INTERVAL 8 HOUR), updated_at = DATE_ADD(updated_at, INTERVAL 8 HOUR);
UPDATE daily_module_snapshot_member SET created_at = DATE_ADD(created_at, INTERVAL 8 HOUR);
UPDATE monthly_memory_card SET created_at = DATE_ADD(created_at, INTERVAL 8 HOUR), updated_at = DATE_ADD(updated_at, INTERVAL 8 HOUR);
UPDATE monthly_memory_card_item SET created_at = DATE_ADD(created_at, INTERVAL 8 HOUR);
UPDATE reminder_subscription SET checkin_notify_last_sent_at = DATE_ADD(checkin_notify_last_sent_at, INTERVAL 8 HOUR), created_at = DATE_ADD(created_at, INTERVAL 8 HOUR), updated_at = DATE_ADD(updated_at, INTERVAL 8 HOUR);
UPDATE idempotency_request SET expire_at = DATE_ADD(expire_at, INTERVAL 8 HOUR), created_at = DATE_ADD(created_at, INTERVAL 8 HOUR), updated_at = DATE_ADD(updated_at, INTERVAL 8 HOUR);
UPDATE outbox_event SET next_retry_at = DATE_ADD(next_retry_at, INTERVAL 8 HOUR), created_at = DATE_ADD(created_at, INTERVAL 8 HOUR), published_at = DATE_ADD(published_at, INTERVAL 8 HOUR);
UPDATE audit_log SET created_at = DATE_ADD(created_at, INTERVAL 8 HOUR);
UPDATE privacy_consent SET agreed_at = DATE_ADD(agreed_at, INTERVAL 8 HOUR), revoked_at = DATE_ADD(revoked_at, INTERVAL 8 HOUR), created_at = DATE_ADD(created_at, INTERVAL 8 HOUR);
UPDATE account_deletion_request SET requested_at = DATE_ADD(requested_at, INTERVAL 8 HOUR), execute_after = DATE_ADD(execute_after, INTERVAL 8 HOUR), cancelled_at = DATE_ADD(cancelled_at, INTERVAL 8 HOUR), completed_at = DATE_ADD(completed_at, INTERVAL 8 HOUR), created_at = DATE_ADD(created_at, INTERVAL 8 HOUR), updated_at = DATE_ADD(updated_at, INTERVAL 8 HOUR);
UPDATE scheduled_job_run SET lock_expires_at = DATE_ADD(lock_expires_at, INTERVAL 8 HOUR), started_at = DATE_ADD(started_at, INTERVAL 8 HOUR), completed_at = DATE_ADD(completed_at, INTERVAL 8 HOUR), created_at = DATE_ADD(created_at, INTERVAL 8 HOUR), updated_at = DATE_ADD(updated_at, INTERVAL 8 HOUR);
UPDATE analytics_event SET occurred_at = DATE_ADD(occurred_at, INTERVAL 8 HOUR), received_at = DATE_ADD(received_at, INTERVAL 8 HOUR);
UPDATE streak_reward_rule SET expires_at = DATE_ADD(expires_at, INTERVAL 8 HOUR), triggered_at = DATE_ADD(triggered_at, INTERVAL 8 HOUR), cancelled_at = DATE_ADD(cancelled_at, INTERVAL 8 HOUR), created_at = DATE_ADD(created_at, INTERVAL 8 HOUR), updated_at = DATE_ADD(updated_at, INTERVAL 8 HOUR);
UPDATE streak_reward_event SET created_at = DATE_ADD(created_at, INTERVAL 8 HOUR);
UPDATE streak_reward_draw SET revealed_at = DATE_ADD(revealed_at, INTERVAL 8 HOUR), created_at = DATE_ADD(created_at, INTERVAL 8 HOUR), updated_at = DATE_ADD(updated_at, INTERVAL 8 HOUR);
UPDATE schema_migration SET applied_at = DATE_ADD(applied_at, INTERVAL 8 HOUR);

SET time_zone = '+08:00';
