CREATE TABLE IF NOT EXISTS memory_collage_board_asset (
  board_asset_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  asset_key VARCHAR(80) NOT NULL,
  name VARCHAR(64) NOT NULL,
  category VARCHAR(40) NOT NULL DEFAULT 'default',
  thumbnail_file_key VARCHAR(512) NOT NULL,
  original_file_key VARCHAR(512) NOT NULL,
  width INT UNSIGNED NOT NULL DEFAULT 1800,
  height INT UNSIGNED NOT NULL DEFAULT 1800,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (board_asset_id),
  UNIQUE KEY uq_memory_collage_board_asset_key (asset_key),
  KEY idx_memory_collage_board_status_order (status, sort_order),
  CONSTRAINT chk_memory_collage_board_status CHECK (status IN ('active', 'retired'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS memory_collage_sticker_asset (
  sticker_asset_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  asset_key VARCHAR(80) NOT NULL,
  name VARCHAR(64) NOT NULL,
  category VARCHAR(40) NOT NULL,
  thumbnail_file_key VARCHAR(512) NOT NULL,
  original_file_key VARCHAR(512) NOT NULL,
  default_width DECIMAL(8,6) NOT NULL DEFAULT 0.180000,
  default_height DECIMAL(8,6) NOT NULL DEFAULT 0.180000,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (sticker_asset_id),
  UNIQUE KEY uq_memory_collage_sticker_asset_key (asset_key),
  KEY idx_memory_collage_sticker_category_order (status, category, sort_order),
  CONSTRAINT chk_memory_collage_sticker_status CHECK (status IN ('active', 'retired'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS memory_collage (
  collage_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  scope_key VARCHAR(80) NOT NULL,
  module_id BIGINT UNSIGNED NULL,
  report_mode VARCHAR(12) NOT NULL,
  period_key VARCHAR(10) NOT NULL,
  board_asset_id BIGINT UNSIGNED NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  version INT UNSIGNED NOT NULL DEFAULT 1,
  saved_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (collage_id),
  UNIQUE KEY uq_memory_collage_scope (user_id, scope_key, report_mode, period_key),
  KEY idx_memory_collage_user_saved (user_id, saved_at),
  KEY idx_memory_collage_module_period (module_id, report_mode, period_key),
  CONSTRAINT fk_memory_collage_user FOREIGN KEY (user_id) REFERENCES user_account(user_id),
  CONSTRAINT fk_memory_collage_module FOREIGN KEY (module_id) REFERENCES life_module(module_id),
  CONSTRAINT fk_memory_collage_board FOREIGN KEY (board_asset_id) REFERENCES memory_collage_board_asset(board_asset_id) ON DELETE SET NULL,
  CONSTRAINT chk_memory_collage_mode CHECK (report_mode IN ('week', 'month')),
  CONSTRAINT chk_memory_collage_status CHECK (status IN ('active', 'deleted'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS memory_collage_item (
  item_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  collage_id BIGINT UNSIGNED NOT NULL,
  asset_type VARCHAR(24) NOT NULL,
  record_id BIGINT UNSIGNED NULL,
  sticker_asset_id BIGINT UNSIGNED NULL,
  position_x DECIMAL(8,6) NOT NULL,
  position_y DECIMAL(8,6) NOT NULL,
  width_ratio DECIMAL(8,6) NOT NULL,
  height_ratio DECIMAL(8,6) NOT NULL,
  rotation_degrees DECIMAL(8,3) NOT NULL DEFAULT 0,
  z_index INT UNSIGNED NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (item_id),
  KEY idx_memory_collage_item_order (collage_id, z_index),
  KEY idx_memory_collage_item_record (record_id),
  KEY idx_memory_collage_item_sticker (sticker_asset_id),
  CONSTRAINT fk_memory_collage_item_collage FOREIGN KEY (collage_id) REFERENCES memory_collage(collage_id) ON DELETE CASCADE,
  CONSTRAINT fk_memory_collage_item_record FOREIGN KEY (record_id) REFERENCES life_record(record_id) ON DELETE SET NULL,
  CONSTRAINT fk_memory_collage_item_sticker FOREIGN KEY (sticker_asset_id) REFERENCES memory_collage_sticker_asset(sticker_asset_id) ON DELETE SET NULL,
  CONSTRAINT chk_memory_collage_item_type CHECK (asset_type IN ('record_sticker', 'decorative_sticker'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
